---
apiVersion: v1
kind: Secret
metadata:
  name: s3glance
stringData:
  s3secret.conf : |
    [default_backend]
    s3_store_host = _s3_endpoint_
    s3_store_access_key = _s3_access_key
    s3_store_secret_key = _s3_secret_key
    s3_store_bucket = _s3_bucket
